repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version pinned to match requirements-dev.txt (0.6.9)
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
